In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import Imputer
# For Preprocessing
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
#from xgboost import XGBClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score
#from xgboost import plot_importance
from sklearn.metrics import confusion_matrix
import numpy as np
from collections import Counter
from sklearn.ensemble import ExtraTreesClassifier
#from xgboost import XGBClassifier
#import xgboost as xgb
from sklearn.base import TransformerMixin
from sklearn.tree import DecisionTreeClassifier
import os
from tqdm import tqdm_notebook as tqdm
from sklearn.externals import joblib
%matplotlib inline
import seaborn as sns
import dask.dataframe as dd
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score,recall_score,precision_score
from imblearn.under_sampling import RandomUnderSampler 
from imblearn.over_sampling import RandomOverSampler

In [2]:
app_train=pd.read_csv("application_train.csv")
app_train.head()
pd.set_option('display.max_columns', None)

In [3]:
app_train.shape

(307511, 122)

In [4]:
app_train['DAYS_EMPLOYED'].replace({365243: np.nan}, inplace = True)

In [5]:
app_train.describe()

SK_ID_CURR         TARGET   CNT_CHILDREN  AMT_INCOME_TOTAL  \
count  307511.000000  307511.000000  307511.000000      3.075110e+05   
mean   278180.518577       0.080729       0.417052      1.687979e+05   
std    102790.175348       0.272419       0.722121      2.371231e+05   
min    100002.000000       0.000000       0.000000      2.565000e+04   
25%    189145.500000       0.000000       0.000000      1.125000e+05   
50%    278202.000000       0.000000       0.000000      1.471500e+05   
75%    367142.500000       0.000000       1.000000      2.025000e+05   
max    456255.000000       1.000000      19.000000      1.170000e+08   

         AMT_CREDIT    AMT_ANNUITY  AMT_GOODS_PRICE  \
count  3.075110e+05  307499.000000     3.072330e+05   
mean   5.990260e+05   27108.573909     5.383962e+05   
std    4.024908e+05   14493.737315     3.694465e+05   
min    4.500000e+04    1615.500000     4.050000e+04   
25%    2.700000e+05   16524.000000     2.385000e+05   
50%    5.135310e+05   24903.000000     4.500000e+05   
75%    8.086500e+05   34596.000000     6.795000e+05   
max    4.050000e+06  258025.500000     4.050000e+06   

       REGION_POPULATION_RELATIVE     DAYS_BIRTH  DAYS_EMPLOYED  \
count               307511.000000  307511.000000  252137.000000   
mean                     0.020868  -16036.995067   -2384.169325   
std                      0.013831    4363.988632    2338.360162   
min                      0.000290  -25229.000000  -17912.000000   
25%                      0.010006  -19682.000000   -3175.000000   
50%                      0.018850  -15750.000000   -1648.000000   
75%                      0.028663  -12413.000000    -767.000000   
max                      0.072508   -7489.000000       0.000000   

       DAYS_REGISTRATION  DAYS_ID_PUBLISH    OWN_CAR_AGE     FLAG_MOBIL  \
count      307511.000000    307511.000000  104582.000000  307511.000000   
mean        -4986.120328     -2994.202373      12.061091       0.999997   
std          3522.886321      1509.450419      11.944812       0.001803   
min        -24672.000000     -7197.000000       0.000000       0.000000   
25%         -7479.500000     -4299.000000       5.000000       1.000000   
50%         -4504.000000     -3254.000000       9.000000       1.000000   
75%         -2010.000000     -1720.000000      15.000000       1.000000   
max             0.000000         0.000000      91.000000       1.000000   

       FLAG_EMP_PHONE  FLAG_WORK_PHONE  FLAG_CONT_MOBILE     FLAG_PHONE  \
count   307511.000000    307511.000000     307511.000000  307511.000000   
mean         0.819889         0.199368          0.998133       0.281066   
std          0.384280         0.399526          0.043164       0.449521   
min          0.000000         0.000000          0.000000       0.000000   
25%          1.000000         0.000000          1.000000       0.000000   
50%          1.000000         0.000000          1.000000       0.000000   
75%          1.000000         0.000000          1.000000       1.000000   
max          1.000000         1.000000          1.000000       1.000000   

          FLAG_EMAIL  CNT_FAM_MEMBERS  REGION_RATING_CLIENT  \
count  307511.000000    307509.000000         307511.000000   
mean        0.056720         2.152665              2.052463   
std         0.231307         0.910682              0.509034   
min         0.000000         1.000000              1.000000   
25%         0.000000         2.000000              2.000000   
50%         0.000000         2.000000              2.000000   
75%         0.000000         3.000000              2.000000   
max         1.000000        20.000000              3.000000   

       REGION_RATING_CLIENT_W_CITY  HOUR_APPR_PROCESS_START  \
count                307511.000000            307511.000000   
mean                      2.031521                12.063419   
std                       0.502737                 3.265832   
min                       1.000000                 0.000000   
25%                       

In [6]:
app_train.iloc[:,1].dtypes

dtype('int64')

In [7]:
for i in range(0,122):
    if(app_train.iloc[:,i].dtypes==object):
        print("col is : ",i,"  ",app_train.iloc[:,i].value_counts())
        print("\n\n")

col is :  2    Cash loans         278232
Revolving loans     29279
Name: NAME_CONTRACT_TYPE, dtype: int64



col is :  3    F      202448
M      105059
XNA         4
Name: CODE_GENDER, dtype: int64



col is :  4    N    202924
Y    104587
Name: FLAG_OWN_CAR, dtype: int64



col is :  5    Y    213312
N     94199
Name: FLAG_OWN_REALTY, dtype: int64



col is :  11    Unaccompanied      248526
Family              40149
Spouse, partner     11370
Children             3267
Other_B              1770
Other_A               866
Group of people       271
Name: NAME_TYPE_SUITE, dtype: int64



col is :  12    Working                 158774
Commercial associate     71617
Pensioner                55362
State servant            21703
Unemployed                  22
Student                     18
Businessman                 10
Maternity leave              5
Name: NAME_INCOME_TYPE, dtype: int64



col is :  13    Secondary / secondary special    218391
Higher education                  74863
Incomplet

In [8]:
# getting the colunms in which we need to apply modeimpute. 
modeimpute=[]
for i in range(0,122):
    if(app_train.iloc[:,i].dtypes=='int64' or app_train.iloc[:,i].dtypes=='float64'):
        if(max(app_train.iloc[:,i])==1 and min(app_train.iloc[:,i])==0):
            if (x in [0,1] for x in app_train.iloc[:,i].value_counts()):
                modeimpute.append(i)
len(modeimpute)


76

In [9]:
objectindex=[]
for i in range(0,122):
    if i not in modeimpute:
        objectindex.append(i)
print(len(objectindex))

46


In [10]:
# newapptraindf=app_train
apptraindfintfloat01=app_train.drop(app_train.columns[objectindex],axis=1)
apptraindfintfloat01.shape

(307511, 76)

In [11]:
apptraindfintfloat01.head()
# this will be mode imputed

TARGET  FLAG_MOBIL  FLAG_EMP_PHONE  FLAG_WORK_PHONE  FLAG_CONT_MOBILE  \
0       1           1               1                0                 1   
1       0           1               1                0                 1   
2       0           1               1                1                 1   
3       0           1               1                0                 1   
4       0           1               1                0                 1   

   FLAG_PHONE  FLAG_EMAIL  REG_REGION_NOT_LIVE_REGION  \
0           1           0                           0   
1           1           0                           0   
2           1           0                           0   
3           0           0                           0   
4           0           0                           0   

   REG_REGION_NOT_WORK_REGION  LIVE_REGION_NOT_WORK_REGION  \
0                           0                            0   
1                           0                            0   
2                           0                            0   
3                           0                            0   
4                           0                            0   

   REG_CITY_NOT_LIVE_CITY  REG_CITY_NOT_WORK_CITY  LIVE_CITY_NOT_WORK_CITY  \
0                       0                       0                        0   
1                       0                       0                        0   
2                       0                       0                        0   
3                       0                       0                        0   
4                       0                       1                        1   

   APARTMENTS_AVG  BASEMENTAREA_AVG  YEARS_BEGINEXPLUATATION_AVG  \
0          0.0247            0.0369                       0.9722   
1          0.0959            0.0529                       0.9851   
2             NaN               NaN                          NaN   
3             NaN               NaN                          NaN   
4             NaN               NaN                          NaN   

   YEARS_BUILD_AVG  COMMONAREA_AVG  ELEVATORS_AVG  ENTRANCES_AVG  \
0           0.6192          0.0143           0.00         0.0690   
1           0.7960          0.0605           0.08         0.0345   
2              NaN             NaN            NaN            NaN   
3              NaN             NaN            NaN            NaN   
4              NaN             NaN            NaN            NaN   

   FLOORSMAX_AVG  FLOORSMIN_AVG  LANDAREA_AVG  LIVINGAPARTMENTS_AVG  \
0         0.0833         0.1250        0.0369                0.0202   
1         0.2917         0.3333        0.0130                0.0773   
2            NaN            NaN           NaN                   NaN   
3            NaN            NaN           NaN                   NaN   
4            NaN            NaN           NaN                   NaN   

   LIVINGAREA_AVG  NONLIVINGAPARTMENTS_AVG  NONLIVINGAREA_AVG  \
0          0.0190                   0.0000             0.0000   
1          0.0549                   0.0039             0.0098   
2             NaN                      NaN                NaN   
3             NaN                      NaN                NaN   
4             NaN                      NaN                NaN   

   APARTMENTS_MODE  BASEMENTAREA_MODE  YEARS_BEGINEXPLUATATION_MODE  \
0           0.0252             0.0383                        0.9722   
1           0.0924             0.0538                        0.9851   
2              NaN                NaN                           NaN   
3              NaN                NaN                           NaN   
4              NaN                NaN                           NaN   

   YEARS_BUILD_MODE  COMMONAREA_MODE  ELEVATORS_MODE  ENTRANCES_MODE  \
0            0.6341           0.0144          0.0000          0.0690   
1            0.8040           0.0497          0.0806          0.0345   
2               NaN              NaN             NaN             NaN   
3         

In [12]:
apptraindfintfloat01.isna().sum().sum()

7696671

In [13]:
mean_imputer = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
mean_imputer = mean_imputer.fit(apptraindfintfloat01)
imputed_df = mean_imputer.transform(apptraindfintfloat01.values)
cols=apptraindfintfloat01.columns
app_train_11=pd.DataFrame(imputed_df,columns=cols)
app_train_11.head()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


TARGET  FLAG_MOBIL  FLAG_EMP_PHONE  FLAG_WORK_PHONE  FLAG_CONT_MOBILE  \
0     1.0         1.0             1.0              0.0               1.0   
1     0.0         1.0             1.0              0.0               1.0   
2     0.0         1.0             1.0              1.0               1.0   
3     0.0         1.0             1.0              0.0               1.0   
4     0.0         1.0             1.0              0.0               1.0   

   FLAG_PHONE  FLAG_EMAIL  REG_REGION_NOT_LIVE_REGION  \
0         1.0         0.0                         0.0   
1         1.0         0.0                         0.0   
2         1.0         0.0                         0.0   
3         0.0         0.0                         0.0   
4         0.0         0.0                         0.0   

   REG_REGION_NOT_WORK_REGION  LIVE_REGION_NOT_WORK_REGION  \
0                         0.0                          0.0   
1                         0.0                          0.0   
2                         0.0                          0.0   
3                         0.0                          0.0   
4                         0.0                          0.0   

   REG_CITY_NOT_LIVE_CITY  REG_CITY_NOT_WORK_CITY  LIVE_CITY_NOT_WORK_CITY  \
0                     0.0                     0.0                      0.0   
1                     0.0                     0.0                      0.0   
2                     0.0                     0.0                      0.0   
3                     0.0                     0.0                      0.0   
4                     0.0                     1.0                      1.0   

   APARTMENTS_AVG  BASEMENTAREA_AVG  YEARS_BEGINEXPLUATATION_AVG  \
0          0.0247            0.0369                       0.9722   
1          0.0959            0.0529                       0.9851   
2          0.0825            0.0000                       0.9871   
3          0.0825            0.0000                       0.9871   
4          0.0825            0.0000                       0.9871   

   YEARS_BUILD_AVG  COMMONAREA_AVG  ELEVATORS_AVG  ENTRANCES_AVG  \
0           0.6192          0.0143           0.00         0.0690   
1           0.7960          0.0605           0.08         0.0345   
2           0.8232          0.0000           0.00         0.1379   
3           0.8232          0.0000           0.00         0.1379   
4           0.8232          0.0000           0.00         0.1379   

   FLOORSMAX_AVG  FLOORSMIN_AVG  LANDAREA_AVG  LIVINGAPARTMENTS_AVG  \
0         0.0833         0.1250        0.0369                0.0202   
1         0.2917         0.3333        0.0130                0.0773   
2         0.1667         0.2083        0.0000                0.0504   
3         0.1667         0.2083        0.0000                0.0504   
4         0.1667         0.2083        0.0000                0.0504   

   LIVINGAREA_AVG  NONLIVINGAPARTMENTS_AVG  NONLIVINGAREA_AVG  \
0          0.0190                   0.0000             0.0000   
1          0.0549                   0.0039             0.0098   
2          0.0000                   0.0000             0.0000   
3          0.0000                   0.0000             0.0000   
4          0.0000                   0.0000             0.0000   

   APARTMENTS_MODE  BASEMENTAREA_MODE  YEARS_BEGINEXPLUATATION_MODE  \
0           0.0252             0.0383                        0.9722   
1           0.0924             0.0538                        0.9851   
2           0.0840             0.0000                        0.9871   
3           0.0840             0.0000                        0.9871   
4           0.0840             0.0000                        0.9871   

   YEARS_BUILD_MODE  COMMONAREA_MODE  ELEVATORS_MODE  ENTRANCES_MODE  \
0            0.6341           0.0144          0.0000          0.0690   
1            0.8040           0.0497          0.0806          0.0345   
2            0.8301           0.0000          0.0000          0.1379   
3         

In [14]:
app_train_11.isna().sum().sum()

0

In [15]:
app_train_11.dtypes.value_counts()

float64    76
dtype: int64

In [16]:
apptraindfobjectandcont=app_train.drop(app_train.columns[modeimpute],axis=1)
apptraindfobjectandcont.shape

pureobject=[]
for i in range(0,46):
    if(apptraindfobjectandcont.iloc[:,i].dtypes=="object"):
        pureobject.append(i)
print(len(pureobject))


16


In [17]:
useful=[x for x in range(0,46) if x not in pureobject]
app_traindf_pureobj=apptraindfobjectandcont.drop(apptraindfobjectandcont.columns[useful],axis=1)
app_traindf_pureobj=pd.get_dummies(app_traindf_pureobj)
app_traindf_pureobj.head()



NAME_CONTRACT_TYPE_Cash loans  NAME_CONTRACT_TYPE_Revolving loans  \
0                              1                                   0   
1                              1                                   0   
2                              0                                   1   
3                              1                                   0   
4                              1                                   0   

   CODE_GENDER_F  CODE_GENDER_M  CODE_GENDER_XNA  FLAG_OWN_CAR_N  \
0              0              1                0               1   
1              1              0                0               1   
2              0              1                0               0   
3              1              0                0               1   
4              0              1                0               1   

   FLAG_OWN_CAR_Y  FLAG_OWN_REALTY_N  FLAG_OWN_REALTY_Y  \
0               0                  0                  1   
1               0                  1                  0   
2               1                  0                  1   
3               0                  0                  1   
4               0                  0                  1   

   NAME_TYPE_SUITE_Children  NAME_TYPE_SUITE_Family  \
0                         0                       0   
1                         0                       1   
2                         0                       0   
3                         0                       0   
4                         0                       0   

   NAME_TYPE_SUITE_Group of people  NAME_TYPE_SUITE_Other_A  \
0                                0                        0   
1                                0                        0   
2                                0                        0   
3                                0                        0   
4                                0                        0   

   NAME_TYPE_SUITE_Other_B  NAME_TYPE_SUITE_Spouse, partner  \
0                        0                                0   
1                        0                                0   
2                        0                                0   
3                        0                                0   
4                        0                                0   

   NAME_TYPE_SUITE_Unaccompanied  NAME_INCOME_TYPE_Businessman  \
0                              1                             0   
1                              0                             0   
2                              1                             0   
3                              1                             0   
4                              1                             0   

   NAME_INCOME_TYPE_Commercial associate  NAME_INCOME_TYPE_Maternity leave  \
0                                      0                                 0   
1                                      0                                 0   
2                                      0                                 0   
3                                      0                                 0   
4                                      0                                 0   

   NAME_INCOME_TYPE_Pensioner  NAME_INCOME_TYPE_State servant  \
0                           0                               0   
1                           0                               1   
2                           0                               0   
3                           0                               0   
4                           0                               0   

   NAME_INCOME_TYPE_Student  NAME_INCOME_TYPE_Unemployed  \
0                         0                            0   
1                         0                            0   
2                         0                            0   
3                         0                            0   
4                         0                            0   

   NAME_INCOME_TYPE_Working  NAME_EDUCATION_TYPE_Academic degree  \
0                         1    

In [18]:
app_traindf_pureobj.isna().sum().sum()

0

In [19]:
app_traindf_meanimpute=apptraindfobjectandcont.drop(apptraindfobjectandcont.columns[pureobject],axis=1)
app_traindf_meanimpute.describe()
print(app_traindf_meanimpute.isna().sum().sum())

746797


In [20]:
temptemp=app_traindf_meanimpute.iloc[:,[-11,-10,-9,-8,-6,-5,-4,-3,-2,-1]]
print(temptemp.isna().sum().sum())
mean_imputer = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
mean_imputer = mean_imputer.fit(temptemp)
imputed_df = mean_imputer.transform(temptemp.values)
cols=temptemp.columns
app_train_temptemp=pd.DataFrame(imputed_df,columns=cols)
# print(app_train_temptemp.head())
print(app_train_temptemp.isna().sum().sum())

253198


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


0


In [21]:
app_traindf_meanimpute.isna().sum().sum()

746797

In [22]:
app_traindf_meanimpute.shape

(307511, 30)

In [23]:
col1=[-11,-10,-9,-8,-6,-5,-4,-3,-2,-1]
col2=[-11+30,-10+30,-9+30,-8+30,-6+30,-5+30,-4+30,-3+30,-2+30,-1+30]
print(col2)
app_traindf_meanimpute2 = app_traindf_meanimpute.drop(app_traindf_meanimpute.columns[col2],axis=1)
print(app_traindf_meanimpute2.isna().sum().sum())

[19, 20, 21, 22, 24, 25, 26, 27, 28, 29]
493599


In [24]:
print(app_traindf_meanimpute2.isna().sum().sum())
mean_imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)
mean_imputer = mean_imputer.fit(app_traindf_meanimpute2)
imputed_df = mean_imputer.transform(app_traindf_meanimpute2.values)
cols=app_traindf_meanimpute2.columns
app_train_14=pd.DataFrame(imputed_df,columns=cols)
app_train_14.head()
# print(app_train_14)
print(app_train_14.isna().sum().sum())

493599


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


0


In [25]:
app_train_14.isna().sum().sum()

0

In [26]:
result = pd.concat([app_train_11,app_traindf_pureobj ,app_train_temptemp ,app_train_14], axis=1, sort=False)
result.head()

TARGET  FLAG_MOBIL  FLAG_EMP_PHONE  FLAG_WORK_PHONE  FLAG_CONT_MOBILE  \
0     1.0         1.0             1.0              0.0               1.0   
1     0.0         1.0             1.0              0.0               1.0   
2     0.0         1.0             1.0              1.0               1.0   
3     0.0         1.0             1.0              0.0               1.0   
4     0.0         1.0             1.0              0.0               1.0   

   FLAG_PHONE  FLAG_EMAIL  REG_REGION_NOT_LIVE_REGION  \
0         1.0         0.0                         0.0   
1         1.0         0.0                         0.0   
2         1.0         0.0                         0.0   
3         0.0         0.0                         0.0   
4         0.0         0.0                         0.0   

   REG_REGION_NOT_WORK_REGION  LIVE_REGION_NOT_WORK_REGION  \
0                         0.0                          0.0   
1                         0.0                          0.0   
2                         0.0                          0.0   
3                         0.0                          0.0   
4                         0.0                          0.0   

   REG_CITY_NOT_LIVE_CITY  REG_CITY_NOT_WORK_CITY  LIVE_CITY_NOT_WORK_CITY  \
0                     0.0                     0.0                      0.0   
1                     0.0                     0.0                      0.0   
2                     0.0                     0.0                      0.0   
3                     0.0                     0.0                      0.0   
4                     0.0                     1.0                      1.0   

   APARTMENTS_AVG  BASEMENTAREA_AVG  YEARS_BEGINEXPLUATATION_AVG  \
0          0.0247            0.0369                       0.9722   
1          0.0959            0.0529                       0.9851   
2          0.0825            0.0000                       0.9871   
3          0.0825            0.0000                       0.9871   
4          0.0825            0.0000                       0.9871   

   YEARS_BUILD_AVG  COMMONAREA_AVG  ELEVATORS_AVG  ENTRANCES_AVG  \
0           0.6192          0.0143           0.00         0.0690   
1           0.7960          0.0605           0.08         0.0345   
2           0.8232          0.0000           0.00         0.1379   
3           0.8232          0.0000           0.00         0.1379   
4           0.8232          0.0000           0.00         0.1379   

   FLOORSMAX_AVG  FLOORSMIN_AVG  LANDAREA_AVG  LIVINGAPARTMENTS_AVG  \
0         0.0833         0.1250        0.0369                0.0202   
1         0.2917         0.3333        0.0130                0.0773   
2         0.1667         0.2083        0.0000                0.0504   
3         0.1667         0.2083        0.0000                0.0504   
4         0.1667         0.2083        0.0000                0.0504   

   LIVINGAREA_AVG  NONLIVINGAPARTMENTS_AVG  NONLIVINGAREA_AVG  \
0          0.0190                   0.0000             0.0000   
1          0.0549                   0.0039             0.0098   
2          0.0000                   0.0000             0.0000   
3          0.0000                   0.0000             0.0000   
4          0.0000                   0.0000             0.0000   

   APARTMENTS_MODE  BASEMENTAREA_MODE  YEARS_BEGINEXPLUATATION_MODE  \
0           0.0252             0.0383                        0.9722   
1           0.0924             0.0538                        0.9851   
2           0.0840             0.0000                        0.9871   
3           0.0840             0.0000                        0.9871   
4           0.0840             0.0000                        0.9871   

   YEARS_BUILD_MODE  COMMONAREA_MODE  ELEVATORS_MODE  ENTRANCES_MODE  \
0            0.6341           0.0144          0.0000          0.0690   
1            0.8040           0.0497          0.0806          0.0345   
2            0.8301           0.0000          0.0000          0.1379   
3         

In [27]:
result.shape

(307511, 246)

In [28]:
result.to_csv("application_train_imputed.csv")

In [29]:
X=pd.read_csv("application_train_imputed.csv")

In [30]:
y=X['TARGET']
X=X.drop('TARGET',axis=1)

def split_train_test(X , y):
    return(train_test_split( X , y , test_size=0.2, random_state=42))

X_train, X_test, y_train, y_test =split_train_test(X,y)

def feature_eng(X_train,y_train,X_test,y_test):
    train_col=list(X_train.columns)
    test_col=list(X_test.columns)    
    clf = ExtraTreesClassifier(n_estimators=50)
    clf = clf.fit(X_train, y_train)
    model = SelectFromModel(clf, prefit=True)
    new_trainX = model.transform(X_train)
    n=np.shape(new_trainX)[1]
    importances = clf.feature_importances_
    indices = np.argsort(importances)[::-1]
    clist=[]
    for f in range(n):     
        clist.append(indices[f])
    new_train_col=[train_col[i] for i in clist]
    new_test_col=[test_col[i] for i in clist]
    X_train=pd.DataFrame(X_train)
    X_test=pd.DataFrame(X_test)
    y_train=pd.DataFrame(y_train)
    y_test=pd.DataFrame(y_test)
    df_new_train=pd.DataFrame(X_train.loc[:,new_train_col],columns=new_train_col)            
    df_new_test=pd.DataFrame(X_test.loc[:,new_test_col],columns=new_test_col)
    print("Improved number of features->",len(clist))    
    return(df_new_train,df_new_test)

df_new_train,df_new_test=feature_eng(X_train, y_train, X_test, y_test)

def run_model_eval_metric(modelname,modelobj,X_train,Y_train,X_test,Y_test):
    # In order to let the models run faster we use dask dataframe
    
    modelobj.fit(X_train,Y_train)
    ypred_train=modelobj.predict(X_train)
    ypred_test=modelobj.predict(X_test)
    y_train_proba = modelobj.predict_proba(X_train)[:,1]
    y_test_proba = modelobj.predict_proba(X_test)[:,1]
    print('\n')
    print(modelname,"model:")
    confmat=confusion_matrix(Y_train,ypred_train)
    print("Train Confusion Matrix:")
    print(confmat)
    confmat=confusion_matrix(Y_test,ypred_test)
    print("Test Confusion Matrix:")
    print(confmat)
    metric=pd.DataFrame([[0]*5]*2,columns=['PRECISION','RECALL','F1_SCORE','ROC_AUC_SCORE','ACCURACY'],index=['Train','Test'],dtype='float32')
    metric['PRECISION']['Train']=round(precision_score(Y_train, ypred_train),3)
    metric['RECALL']['Train']=recall_score(Y_train, ypred_train)
    metric['F1_SCORE']['Train']=round(f1_score(Y_train, ypred_train),3)
    metric['ROC_AUC_SCORE']['Train']=roc_auc_score(Y_train,y_train_proba)
    metric['ACCURACY']['Train']=accuracy_score(Y_train,ypred_train)
    metric['PRECISION']['Test']=precision_score(Y_test, ypred_test)
    metric['RECALL']['Test']=recall_score(Y_test, ypred_test)
    metric['F1_SCORE']['Test']=f1_score(Y_test, ypred_test)
    metric['ROC_AUC_SCORE']['Test']=roc_auc_score(Y_test,y_test_proba)
    metric['ACCURACY']['Test']=accuracy_score(Y_test,ypred_test)
    print(metric)
    
def run_all_models(df_new_train,y_train,df_new_test,y_test):
    # K Nearest Neighbor
    knearest = KNeighborsClassifier(algorithm= 'auto', n_jobs= -1, n_neighbors= 1)
    run_model_eval_metric('K-Nearest Neighbor 1',knearest,df_new_train,y_train,df_new_test,y_test)
    
    knearest = KNeighborsClassifier(algorithm= 'auto', n_jobs= -1, n_neighbors= 3)
    run_model_eval_metric('K-Nearest Neighbor 3',knearest,df_new_train,y_train,df_new_test,y_test)

    # Random Forest
    randfor = RandomForestClassifier(n_estimators= 5, max_features= 'auto', max_depth= 60, bootstrap= True, n_jobs= -1)
    run_model_eval_metric('Random Forest',randfor,df_new_train,y_train,df_new_test,y_test)

    # Decision Trees
    dectree = DecisionTreeClassifier(random_state= 42, max_features= 'auto', max_depth= 40, criterion= 'gini')
    run_model_eval_metric('Decision Tree',dectree,df_new_train,y_train,df_new_test,y_test)

    # Logistic Regression
    logreg = LogisticRegression(penalty = 'l1', class_weight= {0: 0.1, 1: 0.9}, C= 0.5)
    run_model_eval_metric('Logistic Regression',logreg,df_new_train,y_train,df_new_test,y_test)

run_all_models(df_new_train,y_train,df_new_test,y_test)

Improved number of features-> 90


K-Nearest Neighbor 1 model:
Train Confusion Matrix:
[[226132      0]
 [     0  19876]]
Test Confusion Matrix:
[[51984  4570]
 [ 4399   550]]
       PRECISION    RECALL  F1_SCORE  ROC_AUC_SCORE  ACCURACY
Train   1.000000  1.000000  1.000000       1.000000   1.00000
Test    0.107422  0.111134  0.109246       0.515163   0.85417


K-Nearest Neighbor 3 model:
Train Confusion Matrix:
[[224363   1769]
 [ 16032   3844]]
Test Confusion Matrix:
[[55371  1183]
 [ 4773   176]]
       PRECISION    RECALL  F1_SCORE  ROC_AUC_SCORE  ACCURACY
Train   0.685000  0.193399  0.302000       0.934264  0.927641
Test    0.129507  0.035563  0.055802       0.527927  0.903159


Random Forest model:
Train Confusion Matrix:
[[225933    199]
 [  3730  16146]]
Test Confusion Matrix:
[[55718   836]
 [ 4690   259]]
       PRECISION    RECALL  F1_SCORE  ROC_AUC_SCORE  ACCURACY
Train    0.98800  0.812337  0.892000       0.993884  0.984029
Test     0.23653  0.052334  0.085705       0.5959

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)




Logistic Regression model:
Train Confusion Matrix:
[[173630  52502]
 [  8309  11567]]
Test Confusion Matrix:
[[43391 13163]
 [ 2067  2882]]
       PRECISION    RECALL  F1_SCORE  ROC_AUC_SCORE  ACCURACY
Train    0.18100  0.581958  0.276000       0.742232  0.752809
Test     0.17962  0.582340  0.274555       0.743401  0.752370
